singleuser:
  serviceAccountName: redshift
proxy:
  https:
    enabled: true
    type: offload
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<certificate arn>"
hub:
  config:
    Authenticator:
      admin_users:
        - <admin>
      allowed_users:
        - <user 1>
        - <user 2>
    DummyAuthenticator:
      password: <password>
    JupyterHub:
      authenticator_class: dummy